import type { Metadata } from "next"
import { Anuphan, Inter } from "next/font/google"
import "./globals.css"
import { ThemeProvider } from "@/lib/theme-provider"
import "katex/dist/katex.min.css"

const anuphan = Anuphan({
  variable: "--font-anuphan",
  subsets: ["latin"],
})

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "AI Chatbot with LangChain",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${anuphan.variable} ${inter.variable}`}>
         <ThemeProvider
          defaultTheme="system"
          storageKey="ai-chatbot-theme"
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}